// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Persistence;

#nullable disable

namespace WebAPI.Persistence.Migrations
{
    [DbContext(typeof(PadariaDbContext))]
    partial class PadariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Entity.TabFamilia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DesFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IndAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TabFamilia");
                });

            modelBuilder.Entity("WebAPI.Entity.TabProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DesProduto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("des_produto");

                    b.Property<Guid>("Familia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IndAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("tabFamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("tabFamiliaId");

                    b.ToTable("tabProdutos");
                });

            modelBuilder.Entity("WebAPI.Entity.TabProduto", b =>
                {
                    b.HasOne("WebAPI.Entity.TabFamilia", "tabFamilia")
                        .WithMany()
                        .HasForeignKey("tabFamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tabFamilia");
                });
#pragma warning restore 612, 618
        }
    }
}
